<%
  @path = "#{Rubber.root}/config/database.yml"
%>

<%= Rubber.env %>:
  adapter: mysql2
  encoding: utf8
  database: <%= rubber_env.db_name %>
  username: <%= rubber_env.db_user %>
  password: <%= rubber_env.db_pass %>
  host: localhost
  pool: 5
