development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fubuia_development
  pool: 5
  username: root
  password: secret
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fubuia_test
  pool: 5
  username: root
  password: secret
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fubuia_production
  pool: 5
  username: root
  password: secret
  host: localhost

mock:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: fubuia_mock
  pool: 5
  username: root
  password: secret
  host: localhost
