---
- !ruby/object:Rubber::Configuration::InstanceItem
  name: production
  domain: fubuia.com.br
  roles:
  - !ruby/object:Rubber::Configuration::RoleItem
    name: web
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: haproxy
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: app
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: passenger_nginx
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: db
    options:
      primary: true
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: mysql_master
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: collectd
    options: {}
  - !ruby/object:Rubber::Configuration::RoleItem
    name: monit
    options: {}
  instance_id: i-59cc4522
  image_type: m1.small
  image_id: ami-3c994355
  security_groups:
  - fubuia_production_default
  - fubuia_production_web
  - fubuia_production_production
  - fubuia_production_haproxy
  - fubuia_production_app
  - fubuia_production_passenger_nginx
  - fubuia_production_db
  - fubuia_production_mysql
  - fubuia_production_mysql_master
  - fubuia_production_collectd
  - fubuia_production_monit
  external_host: ec2-23-23-77-116.compute-1.amazonaws.com
  external_ip: 23.23.77.116
  internal_host: domU-12-31-39-0C-50-F9.compute-1.internal
  internal_ip: 10.215.83.7
  zone: us-east-1d
  platform: linux
  root_device_type: instance-store
  static_ip: 23.23.77.116
- volumes: {}
  static_ips:
    production: 23.23.77.116
